Added Email,Contact,Country
delta/auction_system pull request #18
Opened 2020-01-01 15:47 UTC by shakti97

It will close #6 issue

2020-01-03 10:20 UTC, ajish-sekar requested changes

2020-01-03 10:20 UTC, ajish-sekar commented on assets/app/jsx/UserRegistration.jsx
>                  console.log(err);
If the submit fails don't just console the error, you have to let the user know it failed, so add some notification or something to let the user know

2020-01-03 18:48 UTC, hariprasanths approved these changes

2020-01-04 03:27 UTC, ajish-sekar approved these changes

2020-01-04 03:28 UTC, merged