Modify socket catalog
delta/auction_system pull request #21
Opened 2020-01-11 16:54 UTC by shakti97

This issue will solve and close #9 and #14 issue

2020-01-11 20:33 UTC, hariprasanths requested changes

2020-01-11 20:33 UTC, hariprasanths commented on assets/app/jsx/AdminPanel.jsx
> +                    console.log(response);
Remove debug logs

2020-01-11 20:33 UTC, hariprasanths commented on assets/app/jsx/AdminPanel.jsx
> +                    console.log('Error in fetching catalog');
Give the error feedback to the user
Show the error message sent from the backend

2020-01-11 20:33 UTC, hariprasanths commented on assets/app/jsx/AdminPanel.jsx
> +                console.log('Some Error Occured');
Show err.message

2020-01-11 20:33 UTC, hariprasanths commented on assets/app/jsx/AdminPanel.jsx
> +                            dataFetch('/saveAuctionSummary', data)
Multiple entries gets added in auction summary for a single item:
2 entries for 2nd item sold
3 for 3rd item sold and so on

2020-01-11 20:33 UTC, hariprasanths commented on assets/app/jsx/AdminPanel.jsx
> +                                                    Sold
sold button in admin panel should only br available after starting the bid

2020-01-12 10:25 UTC, shakti97 commented on assets/app/jsx/AdminPanel.jsx
> +                                                    Sold
Done

2020-01-12 10:25 UTC, shakti97 commented on assets/app/jsx/AdminPanel.jsx
> +                            dataFetch('/saveAuctionSummary', data)
Resolved

2020-01-12 10:25 UTC, shakti97 commented on assets/app/jsx/AdminPanel.jsx
> +                console.log('Some Error Occured');
Resolved

2020-01-12 10:25 UTC, shakti97 commented on assets/app/jsx/AdminPanel.jsx
> +                    console.log('Error in fetching catalog');
Resolved

2020-01-12 10:25 UTC, shakti97 commented on assets/app/jsx/AdminPanel.jsx
> +                    console.log(response);
Resolved

2020-01-12 10:30 UTC, shakti97 commented
Close this , placed another pr( Catalogs ) which includes the recommended changes.

2020-01-16 18:17 UTC, closed without merging