Handled Max User Exceed
delta/auction_system pull request #24
Opened 2020-01-16 21:01 UTC by shakti97

It will resolve and close issue #8

2020-01-17 07:03 UTC, hariprasanths requested changes

2020-01-17 07:03 UTC, hariprasanths commented on app.js
> +    socket.on('joinRoom', (namespace, user_id, max_user) => {
Don't trust the clients to give this info
Associating this with admins is fine

2020-01-17 07:03 UTC, hariprasanths commented on assets/app/jsx/Auction.jsx
> +import Swal from 'sweetalert2';
Bootstrap has an inbuilt model, try using that
We would have one less package need

2020-01-17 07:03 UTC, hariprasanths commented on assets/app/jsx/Auction.jsx
> +            dataFetch('/auctionConfig', {
Write a separate route in the same file instead of using q_type

2020-01-17 07:03 UTC, hariprasanths commented on assets/app/jsx/Auction.jsx
> +                    console.log('Some Error Occured');
Use toastify to notify the user of the error

2020-01-17 07:03 UTC, hariprasanths commented on src/socketRoutes/connectionManager.js
> +        console.log('max_limit_exceeded');
Remove all debug logs

2020-01-20 04:38 UTC, adarshPatel509 commented on app.js
> +        handleConnections.joinAuction(socket, namespace, user_id, max_user);
Remove max_users.  It's already send by adminSocket on openAuction.

2020-01-20 04:38 UTC, adarshPatel509 commented on assets/app/jsx/Auction.jsx
> +            socket.emit('joinRoom', this.state.namespace, this.state.user_id, this.state.max_users);
Remove max_users.

2020-01-20 18:54 UTC, merged