Added Private Auction Functionality
delta/auction_system pull request #25
Opened 2020-01-18 18:43 UTC by shakti97

2020-01-23 07:48 UTC, adarshPatel509 requested changes

2020-01-23 07:48 UTC, adarshPatel509 commented on assets/app/jsx/AdminPanel.jsx
> +            q_type, clientIds,catalogs, sold, start, url_slug, max_users, is_open, can_register, access_type, password} = this.state;
Format it properly. do "$npm run fmt".

2020-01-23 07:48 UTC, adarshPatel509 commented on assets/app/jsx/AdminPanel.jsx
> +                                } else if (!values.max_users) {
also add check for max_users > 0.

2020-01-23 07:48 UTC, adarshPatel509 commented on assets/app/jsx/Home.jsx
> +    };
user can directly goto /auction/slug and will be able to join a protected auction. So, have this check on auctionPage  instead, and create a socket connection only after  auctionAuth success.

2020-01-23 07:48 UTC, adarshPatel509 commented on models/auctionconfig.js
> +      allowNull: false
add this in db_migration file also.

2020-01-23 07:48 UTC, adarshPatel509 commented on src/routes/auctionConfig.js
> +        q_type,
remove q_type and write separate functions for addConfig, getConfig and updateConfig.

2020-01-25 07:07 UTC, adarshPatel509 commented on assets/app/jsx/Auction.jsx
> +        console.log('namespace ', namespace);
remove all debug logs.

2020-01-25 07:10 UTC, adarshPatel509 commented on assets/app/jsx/Home.jsx
> +import Swal from 'sweetalert2';
remove this import. its not used anywhere.

2020-01-25 08:26 UTC, adarshPatel509 approved these changes

2020-01-25 08:31 UTC, hariprasanths requested changes
Reloading the admin panel changes the auction status from private to public

2020-01-25 08:31 UTC, hariprasanths commented on app.js
> +        // console.log('bidding Stop');
remove all unncessary logs

2020-01-25 08:31 UTC, hariprasanths commented on migrations/20191107202814-create-user.js
> -'use strict';
migrations and models needs to be formatted

2020-01-25 09:55 UTC, shakti2379 commented on migrations/20191107202814-create-user.js
> -'use strict';
done

2020-01-25 09:57 UTC, shakti2379 commented on app.js
> +        // console.log('bidding Stop');
done

2020-01-25 10:30 UTC, hariprasanths commented on assets/app/jsx/Auction.jsx
>          this.checkStatus();
Move this to DidMount()

2020-01-25 10:31 UTC, hariprasanths commented on models/auctionconfig.js
> -'use strict';
Format this file

2020-01-25 11:20 UTC, hariprasanths commented on app.js
> +        console.log('disconnect', reason, socket);
Remove this

2020-01-25 19:44 UTC, shakti2379 commented on assets/app/jsx/Auction.jsx
>          this.checkStatus();
Done

2020-01-25 19:44 UTC, shakti2379 commented on models/auctionconfig.js
> -'use strict';
Done

2020-01-25 19:44 UTC, shakti2379 commented on app.js
> +        console.log('disconnect', reason, socket);
Done

2020-01-26 03:57 UTC, hariprasanths approved these changes

2020-01-26 03:58 UTC, merged